{% set name = "aiapy" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiapy-{{ version }}.tar.gz
  sha256: e359b2b897bdcc5b34b53e24828f9695be5b64f8deb7d3e6983fae101e074fbe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - importlib_resources
    - python >=3.6
    - sunpy >=2.0

test:
  requires:
    - pip
    - pytest-astropy
  imports:
    - aiapy
    - aiapy.calibrate
    - aiapy.psf
    - aiapy.response
    - aiapy.util
  commands:
    - pip check
    - pytest --pyargs aiapy --remote-data=any

about:
  home: https://gitlab.com/LMSAL_HUB/aia_hub/aiapy
  summary: Python package for AIA analysis.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - wtbarnes
